package com.sulake.habbo.inventory.events
{
    public class HabboInventoryTrackingEvent 
    {
        public static const HABBO_INVENTORY_TRACKING_EVENT_CLOSED:String = "HABBO_INVENTORY_TRACKING_EVENT_CLOSED";
        public static const HABBO_INVENTORY_TRACKING_EVENT_FURNI:String = "HABBO_INVENTORY_TRACKING_EVENT_FURNI";
        public static const HABBO_INVENTORY_TRACKING_EVENT_POSTERS:String = "HABBO_INVENTORY_TRACKING_EVENT_POSTERS";
        public static const HABBO_INVENTORY_TRACKING_EVENT_BADGES:String = "HABBO_INVENTORY_TRACKING_EVENT_BADGES";
        public static const HABBO_INVENTORY_TRACKING_EVENT_ACHIEVEMENTS:String = "HABBO_INVENTORY_TRACKING_EVENT_ACHIEVEMENTS";
        public static const HABBO_INVENTORY_TRACKING_EVENT_TRADING:String = "HABBO_INVENTORY_TRACKING_EVENT_TRADING";
        public static const HABBO_INVENTORY_TRACKING_EVENT_PETS:String = "HABBO_INVENTORY_TRACKING_EVENT_PETS";
        public static const HABBO_INVENTORY_TRACKING_EVENT_BOTS:String = "HABBO_INVENTORY_TRACKING_EVENT_BOTS";
    }
}
