package com.sulake.habbo.friendlist.events
{
    public class _Str_3797 
    {
        public static const HABBO_FRIENDLIST_TRACKING_EVENT_CLOSED:String = "HABBO_FRIENDLIST_TRACKING_EVENT_CLOSED";
        public static const HABBO_FRIENDLIST_TRACKING_EVENT_FRIENDS:String = "HABBO_FRIENDLIST_TRACKING_EVENT_FRIENDS";
        public static const HABBO_FRIENDLIST_TRACKING_EVENT_SEARCH:String = "HABBO_FRIENDLIST_TRACKING_EVENT_SEARCH";
        public static const HABBO_FRIENDLIST_TRACKING_EVENT_REQUEST:String = "HABBO_FRIENDLIST_TRACKING_EVENT_REQUEST";
        public static const HABBO_FRIENDLIST_TRACKING_EVENT_MINIMZED:String = "HABBO_FRIENDLIST_TRACKING_EVENT_MINIMZED";
        public static const HABBO_FRIENDLIST_TRACKING_EVENT_MESSENGER:String = "HABBO_FRIENDLIST_TRACKING_EVENT_MESSENGER";
    }
}
