package com.sulake.core.window.enum
{
    public class WindowParam 
    {
        public static const WINDOW_PARAM_NULL:uint = 0;
        public static const WINDOW_PARAM_INPUT_EVENT_PROCESSOR:uint = (1 << 0);
        public static const WINDOW_PARAM_ROUTE_INPUT_EVENTS_TO_PARENT:uint = (WINDOW_PARAM_INPUT_EVENT_PROCESSOR | (1 << 1));
        public static const WINDOW_PARAM_OBSERVE_PARENT_INPUT_EVENTS:uint = (WINDOW_PARAM_INPUT_EVENT_PROCESSOR | (1 << 2));
        public static const WINDOW_PARAM_INTERNAL_EVENT_HANDLING:uint = (WINDOW_PARAM_INPUT_EVENT_PROCESSOR | (1 << 3));
        public static const WINDOW_PARAM_USE_PARENT_GRAPHIC_CONTEXT:uint = (1 << 4);
        public static const WINDOW_PARAM_BOUND_TO_PARENT_RECT:uint = (1 << 5);
        public static const WINDOW_PARAM_RELATIVE_HORIZONTAL_SCALE_FIXED:uint = 0;
        public static const WINDOW_PARAM_RELATIVE_HORIZONTAL_SCALE_MOVE:uint = ((1 << 6) | WINDOW_PARAM_RELATIVE_HORIZONTAL_SCALE_FIXED);
        public static const WINDOW_PARAM_RELATIVE_HORIZONTAL_SCALE_STRETCH:uint = ((1 << 7) | WINDOW_PARAM_RELATIVE_HORIZONTAL_SCALE_FIXED);
        public static const WINDOW_PARAM_RELATIVE_HORIZONTAL_SCALE_CENTER:uint = ((WINDOW_PARAM_RELATIVE_HORIZONTAL_SCALE_FIXED | WINDOW_PARAM_RELATIVE_HORIZONTAL_SCALE_MOVE) | WINDOW_PARAM_RELATIVE_HORIZONTAL_SCALE_STRETCH);
        public static const WINDOW_PARAM_RELATIVE_VERTICAL_SCALE_FIXED:uint = 0;
        public static const WINDOW_PARAM_RELATIVE_VERTICAL_SCALE_MOVE:uint = ((1 << 10) | WINDOW_PARAM_RELATIVE_VERTICAL_SCALE_FIXED);
        public static const WINDOW_PARAM_RELATIVE_VERTICAL_SCALE_STRETCH:uint = ((1 << 11) | WINDOW_PARAM_RELATIVE_VERTICAL_SCALE_FIXED);
        public static const WINDOW_PARAM_RELATIVE_VERTICAL_SCALE_CENTER:uint = ((WINDOW_PARAM_RELATIVE_VERTICAL_SCALE_FIXED | WINDOW_PARAM_RELATIVE_VERTICAL_SCALE_MOVE) | WINDOW_PARAM_RELATIVE_VERTICAL_SCALE_STRETCH);
        public static const WINDOW_PARAM_RELATIVE_SCALE_FIXED:uint = (WINDOW_PARAM_RELATIVE_HORIZONTAL_SCALE_FIXED | WINDOW_PARAM_RELATIVE_VERTICAL_SCALE_FIXED);
        public static const WINDOW_PARAM_RELATIVE_SCALE_MOVE:uint = (WINDOW_PARAM_RELATIVE_HORIZONTAL_SCALE_MOVE | WINDOW_PARAM_RELATIVE_VERTICAL_SCALE_MOVE);
        public static const WINDOW_PARAM_RELATIVE_SCALE_STRETCH:uint = (WINDOW_PARAM_RELATIVE_HORIZONTAL_SCALE_STRETCH | WINDOW_PARAM_RELATIVE_VERTICAL_SCALE_STRETCH);
        public static const WINDOW_PARAM_RELATIVE_SCALE_CENTER:uint = (WINDOW_PARAM_RELATIVE_HORIZONTAL_SCALE_CENTER | WINDOW_PARAM_RELATIVE_VERTICAL_SCALE_CENTER);
        public static const WINDOW_PARAM_EXPAND_TO_ACCOMMODATE_CHILDREN:uint = (1 << 17);
        public static const WINDOW_PARAM_RESIZE_TO_ACCOMMODATE_CHILDREN:uint = ((1 << 14) | WINDOW_PARAM_EXPAND_TO_ACCOMMODATE_CHILDREN);
        public static const WINDOW_PARAM_MOUSE_DRAGGING_TARGET:uint = (1 << 15);
        public static const WINDOW_PARAM_MOUSE_DRAGGING_TRIGGER:uint = ((1 << 8) | WINDOW_PARAM_INPUT_EVENT_PROCESSOR);
        public static const WINDOW_PARAM_DRAGGABLE_WITH_MOUSE:uint = (WINDOW_PARAM_MOUSE_DRAGGING_TARGET | WINDOW_PARAM_MOUSE_DRAGGING_TRIGGER);
        public static const WINDOW_PARAM_MOUSE_SCALING_TARGET:uint = (1 << 16);
        public static const WINDOW_PARAM_HORIZONTAL_MOUSE_SCALING_TRIGGER:uint = (1 << 12);
        public static const WINDOW_PARAM_VERTICAL_MOUSE_SCALING_TRIGGER:uint = (1 << 13);
        public static const WINDOW_PARAM_MOUSE_SCALING_TRIGGER:uint = (WINDOW_PARAM_HORIZONTAL_MOUSE_SCALING_TRIGGER | WINDOW_PARAM_VERTICAL_MOUSE_SCALING_TRIGGER);
        public static const WINDOW_PARAM_SCALABLE_WITH_MOUSE:uint = (WINDOW_PARAM_MOUSE_SCALING_TARGET | WINDOW_PARAM_MOUSE_SCALING_TRIGGER);
        public static const WINDOW_PARAM_ON_ACCOMMODATE_ALIGN_LEFT:uint = 0;
        public static const WINDOW_PARAM_ON_ACCOMMODATE_ALIGN_RIGHT:uint = (1 << 18);
        public static const WINDOW_PARAM_ON_ACCOMMODATE_ALIGN_CENTER:uint = ((1 << 19) | WINDOW_PARAM_ON_ACCOMMODATE_ALIGN_RIGHT);
        public static const WINDOW_PARAM_ON_ACCOMMODATE_ALIGN_TOP:uint = 0;
        public static const WINDOW_PARAM_ON_ACCOMMODATE_ALIGN_BOTTOM:uint = (1 << 20);
        public static const WINDOW_PARAM_ON_ACCOMMODATE_ALIGN_MIDDLE:uint = ((1 << 21) | WINDOW_PARAM_ON_ACCOMMODATE_ALIGN_BOTTOM);
        public static const WINDOW_PARAM_ON_ACCOMMODATE_ALIGN_CONTENT:uint = (WINDOW_PARAM_ON_ACCOMMODATE_ALIGN_CENTER | WINDOW_PARAM_ON_ACCOMMODATE_ALIGN_MIDDLE);
        public static const WINDOW_PARAM_ON_RESIZE_ALIGN_LEFT:uint = WINDOW_PARAM_ON_ACCOMMODATE_ALIGN_LEFT;//0
        public static const WINDOW_PARAM_ON_RESIZE_ALIGN_CENTER:uint = WINDOW_PARAM_ON_ACCOMMODATE_ALIGN_CENTER;
        public static const WINDOW_PARAM_ON_RESIZE_ALIGN_RIGHT:uint = WINDOW_PARAM_ON_ACCOMMODATE_ALIGN_RIGHT;
        public static const WINDOW_PARAM_ON_RESIZE_ALIGN_TOP:uint = WINDOW_PARAM_ON_ACCOMMODATE_ALIGN_TOP;//0
        public static const WINDOW_PARAM_ON_RESIZE_ALIGN_MIDDLE:uint = WINDOW_PARAM_ON_ACCOMMODATE_ALIGN_MIDDLE;
        public static const WINDOW_PARAM_ON_RESIZE_ALIGN_BOTTOM:uint = WINDOW_PARAM_ON_ACCOMMODATE_ALIGN_BOTTOM;
        public static const WINDOW_PARAM_ON_RESIZE_ALIGN_HORIZONTAL:uint = ((WINDOW_PARAM_ON_RESIZE_ALIGN_LEFT | WINDOW_PARAM_ON_RESIZE_ALIGN_CENTER) | WINDOW_PARAM_ON_RESIZE_ALIGN_RIGHT);
        public static const WINDOW_PARAM_ON_RESIZE_ALIGN_VERTICAL:uint = ((WINDOW_PARAM_ON_RESIZE_ALIGN_TOP | WINDOW_PARAM_ON_RESIZE_ALIGN_MIDDLE) | WINDOW_PARAM_ON_RESIZE_ALIGN_BOTTOM);
        public static const WINDOW_PARAM_REFLECT_HORIZONTAL_RESIZE_TO_PARENT:uint = (1 << 22);
        public static const WINDOW_PARAM_REFLECT_VERTICAL_RESIZE_TO_PARENT:uint = (1 << 23);
        public static const WINDOW_PARAM_REFLECT_RESIZE_TO_PARENT:uint = (WINDOW_PARAM_REFLECT_HORIZONTAL_RESIZE_TO_PARENT | WINDOW_PARAM_REFLECT_VERTICAL_RESIZE_TO_PARENT);
        public static const WINDOW_PARAM_PARENT_WINDOW:uint = ((WINDOW_PARAM_INPUT_EVENT_PROCESSOR | WINDOW_PARAM_RELATIVE_HORIZONTAL_SCALE_FIXED) | WINDOW_PARAM_RELATIVE_VERTICAL_SCALE_FIXED);
        public static const WINDOW_PARAM_CHILD_WINDOW:uint = (WINDOW_PARAM_INPUT_EVENT_PROCESSOR | WINDOW_PARAM_BOUND_TO_PARENT_RECT);
        public static const WINDOW_PARAM_EMBEDDED_CONTROLLER:uint = (((WINDOW_PARAM_INPUT_EVENT_PROCESSOR | WINDOW_PARAM_BOUND_TO_PARENT_RECT) | WINDOW_PARAM_ROUTE_INPUT_EVENTS_TO_PARENT) | WINDOW_PARAM_USE_PARENT_GRAPHIC_CONTEXT);
        public static const WINDOW_PARAM_FORCE_CLIPPING:uint = (1 << 30);
        public static const WINDOW_PARAM_INHERIT_CAPTION:uint = (1 << 31);
    }
}
