package 
{
    import mx.core.SimpleApplication;
    import com.sulake.bootstrap.HabboNavigatorBootstrap;
    import com.sulake.iid.IIDHabboNavigator;
    import binaryData.*;
    import images.*;

    public class HabboNavigatorCom extends SimpleApplication 
    {
        public static var manifest:Class = _Str_13748;
        public static var arrow_down_white_png:Class = _Str_13587;
        public static var arrow_right_white_png:Class = _Str_14113;
        public static var create_room_png:Class = _Str_15070;
        public static var doormode_doorbell_png:Class = _Str_13344;
        public static var doormode_doorbell_small_png:Class = _Str_12683;
        public static var doormode_password_png:Class = _Str_15068;
        public static var doormode_password_small_png:Class = _Str_15484;
        public static var doormode_invisible_png:Class = _Str_12647;
        public static var doormode_invisible_small_png:Class = _Str_13100;
        public static var enter_room_png:Class = _Str_12779;
        public static var enter_room_l_png:Class = _Str_15858;
        public static var enter_room_m_png:Class = _Str_15597;
        public static var enter_room_r_png:Class = _Str_12901;
        public static var enter_room_a_png:Class = _Str_15314;
        public static var favourite_png:Class = _Str_13900;
        public static var facebook_logo_small_png:Class = _Str_13102;
        public static var group_base_icon_png:Class = _Str_13921;
        public static var make_favourite_png:Class = _Str_14055;
        public static var home_png:Class = _Str_14061;
        public static var make_home_png:Class = _Str_15170;
        public static var icon_weblink_png:Class = _Str_15671;
        public static var icon_hotelview_png:Class = _Str_15517;
        public static var icon_hotelview_reactive_png:Class = _Str_13689;
        public static var navi_room_favourite_png:Class = _Str_15377;
        public static var navi_room_friends_png:Class = _Str_12668;
        public static var navi_room_icon_png:Class = _Str_13948;
        public static var navi_room_official_png:Class = _Str_15023;
        public static var navi_room_own_png:Class = _Str_12709;
        public static var navi_room_popular_png:Class = _Str_14432;
        public static var navi_tag_hot_1_png:Class = HabboNavigatorCom_navi_tag_hot_1_png;
        public static var navi_tag_hot_2_png:Class = HabboNavigatorCom_navi_tag_hot_2_png;
        public static var navi_tag_hot_3_png:Class = HabboNavigatorCom_navi_tag_hot_3_png;
        public static var popup_arrow_down_png:Class = _Str_15840;
        public static var popup_arrow_left_png:Class = _Str_13065;
        public static var popup_arrow_right_png:Class = _Str_15227;
        public static var trading_allowed_png:Class = _Str_12567;
        public static var rico_rnd_m_png:Class = _Str_12889;
        public static var rico_rnd_l_png:Class = _Str_14208;
        public static var rico_rnd_l_b_png:Class = _Str_12868;
        public static var rico_rnd_r_png:Class = _Str_14812;
        public static var rico_rnd_r_b_png:Class = _Str_15800;
        public static var select_arrow_png:Class = _Str_14596;
        public static var tag_l_png:Class = _Str_12896;
        public static var tag_m_png:Class = _Str_14477;
        public static var tag_r_png:Class = _Str_13703;
        public static var tag_l_reactive_png:Class = _Str_15731;
        public static var tag_m_reactive_png:Class = _Str_12573;
        public static var tag_r_reactive_png:Class = _Str_15352;
        public static var thumb_up_png:Class = _Str_13447;
        public static var tile_icon_black_png:Class = _Str_14425;
        public static var tile_icon_white_png:Class = _Str_12696;
        public static var usercount_fixed_b_png:Class = _Str_14571;
        public static var usercount_fixed_g_png:Class = _Str_12562;
        public static var usercount_fixed_o_png:Class = _Str_14459;
        public static var usercount_fixed_r_png:Class = _Str_12630;
        public static var usercount_fixed_y_png:Class = _Str_15329;
        public static var remove_rights_png:Class = _Str_13678;
        public static var grs_front_page_search_big_xml:Class = _Str_15356;
        public static var grs_front_page_search_small_xml:Class = _Str_13421;
        public static var grs_guest_room_details_short_xml:Class = _Str_15135;
        public static var grs_guest_room_details_phase_one_xml:Class = _Str_14249;
        public static var grs_guest_room_details_long_xml:Class = _Str_14065;
        public static var grs_guest_room_thumbnail_xml:Class = _Str_13437;
        public static var grs_room_ads_details_short_xml:Class = _Str_12875;
        public static var grs_room_ads_details_phase_one_xml:Class = _Str_13741;
        public static var grs_hot_room_details_xml:Class = _Str_14155;
        public static var grs_main_window_xml:Class = _Str_13298;
        public static var grs_main_window_new_xml:Class = _Str_15340;
        public static var grs_official_room_row_xml:Class = _Str_15311;
        public static var grs_official_room_row_phase_one_xml:Class = _Str_12657;
        public static var grs_popular_tag_row_xml:Class = _Str_14227;
        public static var grs_promoted_room_category_xml:Class = _Str_15347;
        public static var grs_category_selector_xml:Class = _Str_14941;
        public static var grs_usercount_xml:Class = _Str_13854;
        public static var nav_error_popup_xml:Class = _Str_14126;
        public static var nav_simple_alert_xml:Class = _Str_12685;
        public static var nav_promo_alert_xml:Class = _Str_12679;
        public static var iro_event_settings_xml:Class = _Str_15485;
        public static var iro_event_info_xml:Class = _Str_14074;
        public static var iro_room_details_framed_xml:Class = _Str_14490;
        public static var iro_room_filter_framed_xml:Class = _Str_15682;
        public static var iro_tag_xml:Class = _Str_14555;
        public static var roc_create_room_xml:Class = _Str_13500;
        public static var roc_vip_promo_xml:Class = _Str_14269;
        public static var roc_room_thumbnail_xml:Class = _Str_14716;
        public static var ros_flat_controller_xml:Class = _Str_15825;
        public static var ros_banned_user_xml:Class = _Str_14300;
        public static var ros_friend_xml:Class = _Str_13632;
        public static var ros_badword_xml:Class = _Str_12590;
        public static var ros_room_settings_xml:Class = _Str_13165;
        public static var ros_confirm_xml:Class = _Str_15548;
        public static var password_input_xml:Class = _Str_13326;
        public static var doorbell_xml:Class = _Str_15209;
        public static var guild_info_xml:Class = _Str_15367;
        public static var toolbar_hover_xml:Class = _Str_14409;
        public static var enforce_category_xml:Class = _Str_15562;
        public static var requiredClasses:Array = new Array(HabboNavigatorBootstrap, IIDHabboNavigator);
    }
}
