package com.sulake.core.window.theme
{
    import flash.text.AntiAliasType;
    import com.sulake.core.window.utils.TextStyle;
    import com.sulake.core.window.enum.LinkTarget;
    import com.sulake.core.window.enum.PivotPoint;

    public class PropertyKeys 
    {
        public static const ALWAYS_SHOW_SELECTION:String = "always_show_selection";
        public static const ANTIALIAS_TYPE:String = "antialias_type";
        public static const ASSET_URI:String = "asset_uri";
        public static const AUTO_ARRANGE_ITEMS:String = "auto_arrange_items";
        public static const AUTO_SIZE:String = "auto_size";
        public static const BITMAP_ASSET_NAME:String = "bitmap_asset_name";
        public static const BORDER:String = "border";
        public static const BORDER_COLOR:String = "border_color";
        public static const CONDENSE_WHITE:String = "condense_white";
        public static const CONTAINER_RESIZE_TO_COLUMNS:String = "container_resize_to_columns";
        public static const DIRECTION:String = "direction";
        public static const DISPLAY_AS_PASSWORD:String = "display_as_password";
        public static const DISPLAY_RAW:String = "display_raw";
        public static const EDITABLE:String = "editable";
        public static const FIT_SIZE_TO_CONTENTS:String = "fit_size_to_contents";
        public static const FOCUS_CAPTURER:String = "focus_capturer";
        public static const GREYSCALE:String = "greyscale";
        public static const GRID_FIT_TYPE:String = "grid_fit_type";
        public static const HANDLE_BITMAP_DISPOSING:String = "handle_bitmap_disposing";
        public static const HELP_PAGE:String = "help_page";
        public static const LINK_TARGET:String = "link_target";
        public static const ITEM_SPACING:String = "spacing";
        public static const KEEP_OPEN_ON_DEACTIVATE:String = "keep_open_on_deactivate";
        public static const MARGIN_LEFT:String = "margin_left";
        public static const MARGIN_TOP:String = "margin_top";
        public static const MARGIN_RIGHT:String = "margin_right";
        public static const MARGIN_BOTTOM:String = "margin_bottom";
        public static const MAX_CHARS:String = "max_chars";
        public static const MAX_LINES:String = "max_lines";
        public static const MENU_ITEM_ARRAY:String = "item_array";
        public static const MOUSE_WHEEL_ENABLED:String = "mouse_wheel_enabled";
        public static const MULTILINE:String = "multiline";
        public static const OPEN_UPWARD:String = "open_upward";
        public static const PADDING_HORIZONTAL:String = "padding_horizontal";
        public static const PADDING_VERTICAL:String = "padding_vertical";
        public static const PIVOT_POINT:String = "pivot_point";
        public static const POINTER_OFFSET:String = "pointer_offset";
        public static const RESIZE_ON_ITEM_UPDATE:String = "resize_on_item_update";
        public static const RESTRICT:String = "restrict";
        public static const SCALE_TO_FIT_ITEMS:String = "scale_to_fit_items";
        public static const SCROLLABLE:String = "scrollable";
        public static const SCROLL_STEP_HORIZONTAL:String = "scroll_step_h";
        public static const SCROLL_STEP_VERTICAL:String = "scroll_step_v";
        public static const SELECTABLE:String = "selectable";
        public static const STRETCHED_X:String = "stretched_x";
        public static const STRETCHED_Y:String = "stretched_y";
        public static const TEXT_COLOR:String = "text_color";
        public static const TEXT_STYLE:String = "text_style";
        public static const TOOL_TIP_CAPTION:String = "tool_tip_caption";
        public static const TOOL_TIP_DELAY:String = "tool_tip_delay";
        public static const TOOL_TIP_IS_DYNAMIC:String = "tool_tip_is_dynamic";
        public static const VERTICAL:String = "vertical";
        public static const WIDGET_TYPE:String = "widget_type";
        public static const WORD_WRAP:String = "word_wrap";
        public static const WRAP_X:String = "wrap_x";
        public static const WRAP_Y:String = "wrap_y";
        public static const ZOOM_X:String = "zoom_x";
        public static const ZOOM_Y:String = "zoom_y";
        public static const OVERFLOW_REPLACE:String = "overflow_replace";
        public static const TEST_ID:String = "test_id_key";
        public static const BOLD:String = "bold";
        public static const ETCHING_COLOR:String = "etching_color";
        public static const ETCHING_POSITION:String = "etching_position";
        public static const FONT_FACE:String = "font_face";
        public static const FONT_SIZE:String = "font_size";
        public static const ITALIC:String = "italic";
        public static const KERNING:String = "kerning";
        public static const LEADING:String = "leading";
        public static const SHARPNESS:String = "sharpness";
        public static const SPACING:String = "spacing";
        public static const THICKNESS:String = "thickness";
        public static const UNDERLINE:String = "underline";
        public static const ANTIALIAS_TYPE_RANGE:Array = [AntiAliasType.NORMAL, AntiAliasType.ADVANCED];
        public static const ETCHING_POSITION_RANGE:Array = [TextStyle.TOP_LEFT, TextStyle.TOP, TextStyle.TOP_RIGHT, TextStyle.LEFT, TextStyle.RIGHT, TextStyle.BOTTOM_LEFT, TextStyle.BOTTOM, TextStyle.BOTTOM_RIGHT];
        public static const HTML_LINK_TARGET_VALUE:String = LinkTarget.DEFAULT;
        public static const HTML_LINK_TARGET_RANGE:Array = [LinkTarget.DEFAULT, LinkTarget.BLANK, LinkTarget.PARENT, LinkTarget.SELF, LinkTarget.TOP, LinkTarget.INTERNAL];
        public static const PIVOT_POINT_RANGE:Array = PivotPoint.PIVOT_NAMES;
    }
}
